import githubMarkdownCss from "generate-github-markdown-css";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { paths } from "../shared/paths";

export const githubMarkdownCssFile: string = "github-markdown.css";
export const githubThemeNames: readonly GithubTheme[] = [
  "light",
  "light_colorblind",
  "light_high_contrast",
  "light_tritanopia",
  "dark",
  "dark_colorblind",
  "dark_dimmed",
  "dark_high_contrast",
  "dark_tritanopia"
];

const markdownRoot = ".vscode-github-markdown";

type GithubTheme =
  | "light"
  | "light_colorblind"
  | "light_high_contrast"
  | "light_tritanopia"
  | "dark"
  | "dark_colorblind"
  | "dark_dimmed"
  | "dark_high_contrast"
  | "dark_tritanopia";

type CssAsset = {
  fileName: string;
  content: string;
};

type ThemeCssParts = {
  theme: GithubTheme;
  sharedVariables: string;
  themeVariables: string;
};

export async function writeGithubCssFiles(outputDir: string = paths.dist): Promise<void> {
  await mkdir(outputDir, { recursive: true });

  for (const asset of await createGithubCssAssets()) {
    await writeIfChanged(join(outputDir, asset.fileName), asset.content);
  }
}

export function githubCssImportBlock(): string {
  return githubCssFileNames()
    .map((fileName) => `@import "./${fileName}";`)
    .join("\n");
}

export function githubCssFileNames(): string[] {
  return [
    githubMarkdownCssFile,
    ...githubThemeNames.map((theme) => `github-markdown-theme-${theme}.css`)
  ];
}

export async function createGithubCssAssets(): Promise<CssAsset[]> {
  const [markdownStyles, ...themes] = await Promise.all([
    githubMarkdownCss({ onlyStyles: true, rootSelector: markdownRoot }),
    ...githubThemeNames.map((theme) => readThemeCssParts(theme))
  ]);

  const sharedVariables = themes[0]?.sharedVariables;
  if (!sharedVariables) {
    throw new Error("GitHub CSS shared variables were not generated.");
  }
  if (markdownStyles.includes("[data-theme=")) {
    throw new Error("GitHub Markdown styles unexpectedly include theme selectors.");
  }

  for (const theme of themes) {
    if (theme.sharedVariables !== sharedVariables) {
      throw new Error(`GitHub CSS shared variables changed while generating ${theme.theme}.`);
    }
  }

  return [
    {
      fileName: githubMarkdownCssFile,
      content: withGeneratedHeader(`${sharedVariables}\n\n${markdownStyles}`)
    },
    ...themes.map((theme) => ({
      fileName: `github-markdown-theme-${theme.theme}.css`,
      content: withGeneratedHeader(themeCss(theme.theme, theme.themeVariables))
    }))
  ];
}

async function readThemeCssParts(theme: GithubTheme): Promise<ThemeCssParts> {
  const css = await githubMarkdownCss({
    light: theme,
    dark: theme,
    onlyVariables: true,
    rootSelector: markdownRoot
  });
  const selector = `${markdownRoot},\n[data-theme="${theme}"] {\n`;
  const selectorIndex = css.indexOf(selector);
  const blockEnd = css.lastIndexOf("\n}");

  if (selectorIndex === -1 || blockEnd === -1 || blockEnd <= selectorIndex) {
    throw new Error(`Could not split GitHub CSS variables for ${theme}.`);
  }

  return {
    theme,
    sharedVariables: css.slice(0, selectorIndex).trim(),
    themeVariables: css.slice(selectorIndex + selector.length, blockEnd)
  };
}

function themeCss(theme: GithubTheme, variables: string): string {
  return [
    `${markdownRoot}[data-color-mode="light"][data-light-theme="${theme}"],
${markdownRoot}[data-color-mode="dark"][data-dark-theme="${theme}"] {
${variables}
}`,
    `@media (prefers-color-scheme: light) {
  ${markdownRoot}[data-color-mode="auto"][data-light-theme="${theme}"] {
${indent(variables, "  ")}
  }
}`,
    `@media (prefers-color-scheme: dark) {
  ${markdownRoot}[data-color-mode="auto"][data-dark-theme="${theme}"] {
${indent(variables, "  ")}
  }
}`
  ].join("\n\n");
}

function indent(value: string, prefix: string): string {
  return value
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n");
}

function withGeneratedHeader(css: string): string {
  return `/* Generated by scripts/build.ts and scripts/dev.ts. Do not edit. */\n\n${css}\n`;
}

async function writeIfChanged(file: string, next: string): Promise<void> {
  try {
    if ((await readFile(file, "utf8")) === next) {
      return;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }

  await writeFile(file, next);
}
