import { Buffer } from "node:buffer";
import { caseFold } from "unicode-case-folding";

export interface GeneratedCaseFolding {
  source: string;
  entries: number;
  byteLength: number;
}

export function generateCaseFoldingSource(): GeneratedCaseFolding {
  const bytes: number[] = [];
  let entries = 0;
  let previousCodePoint = 0;

  function writeVarint(value: number): void {
    while (value >= 0x80) {
      bytes.push((value & 0x7f) | 0x80);
      value >>>= 7;
    }
    bytes.push(value);
  }

  function zigzag(value: number): number {
    return ((value << 1) ^ (value >> 31)) >>> 0;
  }

  for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
    if (codePoint >= 0xd800 && codePoint <= 0xdfff) continue;

    const source = String.fromCodePoint(codePoint);
    const target = caseFold(source);
    if (source === target) continue;

    const targetCodePoints = Array.from(target, (character) => character.codePointAt(0)!);
    writeVarint(codePoint - previousCodePoint);
    writeVarint(targetCodePoints.length);
    for (const targetCodePoint of targetCodePoints) {
      writeVarint(zigzag(targetCodePoint - codePoint));
    }
    previousCodePoint = codePoint;
    entries += 1;
  }

  const data = Buffer.from(bytes).toString("base64");
  const source = `// Generated by \`nub run update:case-folding\`. Do not edit manually.

const caseFoldingData =
  "${data}";
const base64Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function decodeBase64(input: string): Uint8Array {
  const output = new Uint8Array(Math.floor((input.length * 3) / 4));
  let accumulator = 0;
  let bits = 0;
  let outputOffset = 0;

  for (const character of input) {
    if (character === "=") break;
    accumulator = (accumulator << 6) | base64Alphabet.indexOf(character);
    bits += 6;
    if (bits < 8) continue;
    bits -= 8;
    output[outputOffset] = (accumulator >>> bits) & 0xff;
    outputOffset += 1;
  }

  return output.subarray(0, outputOffset);
}

const caseFoldingBytes = decodeBase64(caseFoldingData);
const caseFoldings = new Map<string, string>();
let byteOffset = 0;
let sourceCodePoint = 0;

function readVarint(): number {
  let value = 0;
  let shift = 0;
  while (true) {
    const byte = caseFoldingBytes[byteOffset++]!;
    value |= (byte & 0x7f) << shift;
    if ((byte & 0x80) === 0) return value >>> 0;
    shift += 7;
  }
}

function unzigzag(value: number): number {
  return (value >>> 1) ^ -(value & 1);
}

while (byteOffset < caseFoldingBytes.length) {
  sourceCodePoint += readVarint();
  const targetLength = readVarint();
  const targetCodePoints: number[] = [];
  for (let index = 0; index < targetLength; index += 1) {
    targetCodePoints.push(sourceCodePoint + unzigzag(readVarint()));
  }
  caseFoldings.set(
    String.fromCodePoint(sourceCodePoint),
    String.fromCodePoint(...targetCodePoints)
  );
}

export function caseFold(input: string): string {
  const result: string[] = [];
  for (const character of input) result.push(caseFoldings.get(character) ?? character);
  return result.join("");
}
`;

  return { source, entries, byteLength: bytes.length };
}
